name: Clear jsDelivr Cache
on:
  push:
    branches:
      - main

jobs:
  clearCache:
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run clear_jsdelivr_cache.sh
      run: |
        chmod +x mac-config/rule/clear_jsdelivr_cache.sh
        ./mac-config/rule/clear_jsdelivr_cache.sh
