name: Convert Markdown to HTML and Deploy

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
    paths:
      - 'win_xnj.md'  # 只有当 win_xnj.md 文件变更时触发

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo (mac-config)
        uses: actions/checkout@v4
        with:
          repository: summer19940609/mac-config
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Markdown to HTML
        run: |
          # 安装 pandoc（Markdown 转换工具）
          sudo apt-get install -y pandoc

          # 使用 pandoc 将 win_xnj.md 转换为 win_xnj.html
          pandoc win_xnj.md -o win_xnj.html

      - name: Commit HTML to current repo (mac-config)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add win_xnj.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generated HTML from win_xnj.md"
            git push
          fi

      - name: Checkout target repo (verygoodbye)
        uses: actions/checkout@v4
        with:
          repository: summer19940609/verygoodbye
          token: ${{ secrets.DEPLOY_TOKEN }}  # 使用 PAT
          path: verygoodbye
      
      - name: Commit and push to target repo (verygoodbye)
        run: |
          cd verygoodbye
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
          git add win-xnj.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-deploy win-xnj.html from mac-config"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}  # 确保 push 时使用 PAT
