name: Convert Markdown to HTML and Deploy

on:
  push:
    branches: [main]
    paths: ['win_xnj.md']

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mac-config
        uses: actions/checkout@v4

      - name: Convert Markdown to HTML
        run: |
          sudo apt-get install -y pandoc
          pandoc win_xnj.md -o win_xnj.html
          echo "<!-- Generated at $(date) -->" >> win_xnj.html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to verygoodbye
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          repository: summer19940609/verygoodbye
          branch: main
          force: true
          directory: .
          target_branch: main
          source_file: "win_xnj.html"
          destination_file: "win-xnj.html"
