name: 自动转换README并同步到verygoodbye仓库

on:
  push:
    paths:
      - 'README.md'

jobs:
  convert_and_sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予写入权限

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # 关键修复1：显式传递token

      - name: 用Pandoc转换MD为HTML
        uses: docker://pandoc/core:latest
        with:
          args: "README.md -s -o README.html"
          
      - name: 同步到verygoodbye仓库
        run: |
          # 配置Git身份
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          
          # 关键修复2：使用完整克隆语法
          repo_url="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/summer19940609/verygoodbye.git"
          git clone $repo_url
          
          # 处理文件
          cp README.html verygoodbye/mac.html
          
          # 提交变更
          cd verygoodbye
          git add mac.html
          
          # 关键修复3：添加错误处理
          if ! git diff-index --quiet HEAD --; then
            git commit -m "自动更新mac.html [$(date +'%Y-%m-%d %H:%M')]"
            git push $repo_url HEAD:main
          else
            echo "没有检测到文件变更"
          fi

      - name: 提交HTML到当前仓库
        if: always()  # 即使上一步失败也执行
        run: |
          git add README.html
          if ! git diff-index --quiet HEAD --; then
            git commit -m "自动生成README.html [$(date +'%Y-%m-%d %H:%M')]"
            git push
          fi
