name: 自动转换README并同步到verygoodbye仓库

on:
  push:
    paths:
      - 'README.md'

jobs:
  convert_and_sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键授权：允许工作流写入仓库内容

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true  # 保持认证状态

      - name: 用Pandoc转换MD为HTML
        uses: docker://pandoc/core:latest
        with:
          args: "README.md -s -o README.html"
          
      - name: 同步到verygoodbye仓库
        run: |
          # 配置Git用户（必须设置）
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

          # 克隆目标仓库（使用同一账户下的令牌）
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/summer19940609/verygoodbye.git
          
          # 复制并重命名文件
          cp README.html verygoodbye/mac.html
          
          # 提交变更
          cd verygoodbye
          git add mac.html
          if git commit -m "自动更新mac.html [由工作流触发]"; then
            git push origin HEAD
          else
            echo "没有检测到文件变更，跳过提交"
          fi

      - name: 提交HTML到当前仓库
        run: |
          git add README.html
          if git commit -m "自动生成README.html [由工作流触发]"; then
            git push origin HEAD
          else
            echo "没有检测到文件变更，跳过提交"
          fi
