name: Convert Markdown to HTML and Deploy

on:
  push:
    branches: [main]
    paths: ['README.md']

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mac-config
        uses: actions/checkout@v4

      - name: Convert Markdown to HTML
        run: |
          sudo apt-get install -y pandoc
          pandoc --standalone --self-contained --css pandoc.css README.md --output README.html
          echo "<!-- Generated at $(date) -->" >> README.html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to verygoodbye
        uses: actions/checkout@v4
        with:
          repository: summer19940609/verygoodbye
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: verygoodbye

      - name: Copy and Commit
        run: |
          cp README.html verygoodbye/mac.html
          cd verygoodbye
          git add mac.html
          git commit -m "Auto-update mac.html (generated at $(date))"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
